### ISSUE TITLE
Docker Hub support

### ISSUE THREAD

**Issue by jphorn** [Sebastix/crypto-dca#6]
Since not everyone is a code wizard, support for prebuild Docker images (`docker pull`) on Docker Hub (like https://github.com/Jorijn/bitcoin-dca) would be awesome.

Explanation: I have this running on my very old mac Mini, but it currently only runs Docker. I don't have git installed. With docker pull I only have to retrieve the latest build directly from Docker Hub.

**Comment by Sebastix** [comment]
Noted, I prefer to use the Github container registry for pulling the image for this feature. Docker is monitezing their Docker hub storage.

**Comment by Sebastix** [comment]
The image is now available as a Github package: https://github.com/Sebastix/crypto-dca/pkgs/container/crypto-dca
